stages:
  - build

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  # Registry paths
  REGISTRY_HOST: $CI_REGISTRY
  IMAGE_BACKEND: $CI_REGISTRY_IMAGE/backend
  IMAGE_DASHBOARD: $CI_REGISTRY_IMAGE/dashboard
  IMAGE_INGESTER: $CI_REGISTRY_IMAGE/ingester
  IMAGE_BACKUP: $CI_REGISTRY_IMAGE/backup

services:
  - name: docker:24.0.5-dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-all:
  stage: build
  image: docker:24.0.5
  script:
    # Backend
    - docker build -t $IMAGE_BACKEND:latest -t $IMAGE_BACKEND:$CI_COMMIT_SHORT_SHA ./backend
    - docker push $IMAGE_BACKEND:latest
    - docker push $IMAGE_BACKEND:$CI_COMMIT_SHORT_SHA
    
    # Dashboard
    - docker build -t $IMAGE_DASHBOARD:latest -t $IMAGE_DASHBOARD:$CI_COMMIT_SHORT_SHA ./dashboard
    - docker push $IMAGE_DASHBOARD:latest
    - docker push $IMAGE_DASHBOARD:$CI_COMMIT_SHORT_SHA
    
    # Ingester
    - docker build -t $IMAGE_INGESTER:latest -t $IMAGE_INGESTER:$CI_COMMIT_SHORT_SHA ./ingester
    - docker push $IMAGE_INGESTER:latest
    - docker push $IMAGE_INGESTER:$CI_COMMIT_SHORT_SHA
    
    # Backup
    - docker build -t $IMAGE_BACKUP:latest -t $IMAGE_BACKUP:$CI_COMMIT_SHORT_SHA ./backup
    - docker push $IMAGE_BACKUP:latest
    - docker push $IMAGE_BACKUP:$CI_COMMIT_SHORT_SHA
  only:
    - main
