services:
  otel-agent:
    image: otel/opentelemetry-collector-contrib:0.110.0
    container_name: otel-agent
    restart: unless-stopped

    user: "0"
    read_only: true

    volumes:
      - ./agent-config.yaml:/etc/otel/config.yaml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - otel_checkpoint:/var/lib/otelcol

    command: [ "--config=/etc/otel/config.yaml" ]

    tmpfs:
      - /tmp

    security_opt:
      - no-new-privileges:true

volumes:
  otel_checkpoint:
