services:
  vector-containers:
    image: timberio/vector:0.54.0-alpine
    container_name: vector-containers
    restart: unless-stopped
    user: root
    command: [ "--config", "/etc/vector/vector.toml" ]
    volumes:
      - ./vector.toml:/etc/vector/vector.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
